class AdsPowerError(Exception): ...
class AdsPowerConnectionError(AdsPowerError): ...
class AdsPowerApiError(AdsPowerError):
    def __init__(self, message: str, code: int = 0):
        super().__init__(message)
        self.code = code
class AdsPowerStuckError(AdsPowerApiError): ...
